spring.application.name=order-service

server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/order_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

product.service.url=${PRODUCT_SERVICE_URL:http://product-service:8081}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always